LESSONS = [
    "🐝 Honey never spoils. Archaeologists have found 3,000-year-old honey in Egyptian tombs that's still edible.",
    "🌍 The Earth's core is as hot as the surface of the Sun — about 5,500°C.",
    "📚 Reading for just 15 minutes a day exposes you to over 1 million words per year.",
    "🧠 Your brain uses about 20% of your body's total energy.",
    "💧 Water is the only substance on Earth that exists naturally as solid, liquid, and gas.",
    "🦈 Sharks existed before trees. Sharks are ~450 million years old; trees are ~350 million.",
    "🌕 The Moon is drifting away from Earth at about 3.8 cm per year.",
    "🐙 Octopuses have three hearts and blue blood.",
    "⚡ A bolt of lightning is roughly five times hotter than the surface of the Sun.",
    "🍯 Bees must visit about 2 million flowers to make one pound of honey.",
    "🌊 More than 80% of the ocean remains unexplored.",
    "🦴 A human baby has about 300 bones, but adults have 206.",
    "🚀 The first computer programmer was Ada Lovelace, in the 1840s.",
    "🌱 Bamboo can grow up to 91 cm in a single day.",
    "🐜 Ants can lift up to 50 times their own body weight.",
    "❄️ Snowflakes are not perfectly symmetrical — each arm grows differently.",
    "📖 The longest novel ever written is 'In Search of Lost Time' by Marcel Proust.",
    "🔭 There are more stars in the universe than grains of sand on Earth.",
    "🦩 Flamingos are pink because of the shrimp they eat.",
    "🐘 Elephants are the only mammals that can't jump.",
]

TIPS = [
    "💡 Use the Pomodoro Technique: 25 minutes of focus, 5 minutes of break.",
    "💡 Teach what you learn — it's the fastest way to master a topic.",
    "💡 Sleep is when your brain files away memories. Don't skip it before exams.",
    "💡 Write notes by hand — it improves retention more than typing.",
    "💡 Review new material within 24 hours to fight the forgetting curve.",
    "💡 Study in short bursts with breaks — your brain retains more.",
    "💡 Explain a concept out loud as if teaching a child. If you stumble, you don't know it yet.",
    "💡 Turn off notifications while studying. Multitasking kills focus.",
    "💡 Drink water before and during study sessions — dehydration hurts concentration.",
    "💡 Test yourself instead of re-reading. Active recall beats passive review.",
    "💡 Study at the same time each day to build a habit loop.",
    "💡 Write down 3 things you learned after each session.",
    "💡 Use mnemonics for lists — your brain loves patterns.",
    "💡 Break big topics into small chunks. Master one before moving on.",
    "💡 Get 7–9 hours of sleep. Memory consolidation happens during deep sleep.",
]

WORDS = [
    ("Ephemeral", "Lasting for a very short time.", "The ephemeral beauty of cherry blossoms."),
    ("Serendipity", "Finding something good without looking for it.", "It was pure serendipity that we met."),
    ("Resilience", "The ability to recover quickly from difficulties.", "Her resilience inspired the whole team."),
    ("Eloquent", "Fluent or persuasive in speaking or writing.", "He gave an eloquent speech."),
    ("Pragmatic", "Dealing with things sensibly and realistically.", "She took a pragmatic approach to the problem."),
    ("Tenacious", "Keeping a firm hold; persistent.", "He was tenacious in pursuing his goals."),
    ("Ambiguous", "Open to more than one interpretation.", "The instructions were ambiguous."),
    ("Meticulous", "Showing great attention to detail.", "She kept meticulous records."),
    ("Candid", "Truthful and straightforward.", "He gave a candid interview."),
    ("Innovative", "Introducing new ideas; original and creative.", "The team proposed an innovative solution."),
    ("Empathy", "The ability to understand and share the feelings of another.", "She listened with empathy."),
    ("Perseverance", "Persistence in doing something despite difficulty.", "His perseverance paid off in the end."),
    ("Prudent", "Acting with care and thought for the future.", "It was a prudent decision."),
    ("Articulate", "Able to express ideas clearly and effectively.", "She is an articulate speaker."),
    ("Versatile", "Able to adapt to many different functions or activities.", "He is a versatile player."),
]

QUIZZES = [
    {"q": "What is the capital of Japan?", "options": ["Beijing", "Tokyo", "Seoul", "Bangkok"], "answer": "Tokyo"},
    {"q": "How many continents are there on Earth?", "options": ["5", "6", "7", "8"], "answer": "7"},
    {"q": "What is 12 × 12?", "options": ["124", "144", "132", "154"], "answer": "144"},
    {"q": "Which planet is known as the Red Planet?", "options": ["Venus", "Mars", "Jupiter", "Mercury"], "answer": "Mars"},
    {"q": "What is the largest ocean on Earth?", "options": ["Atlantic", "Indian", "Pacific", "Arctic"], "answer": "Pacific"},
    {"q": "Who wrote 'Romeo and Juliet'?", "options": ["Dickens", "Shakespeare", "Tolstoy", "Hemingway"], "answer": "Shakespeare"},
    {"q": "What gas do plants absorb from the air?", "options": ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], "answer": "Carbon Dioxide"},
    {"q": "How many sides does a hexagon have?", "options": ["5", "6", "7", "8"], "answer": "6"},
    {"q": "What is the chemical symbol for gold?", "options": ["Go", "Gd", "Au", "Ag"], "answer": "Au"},
    {"q": "Which country invented paper?", "options": ["India", "China", "Egypt", "Greece"], "answer": "China"},
    {"q": "What is the square root of 81?", "options": ["7", "8", "9", "10"], "answer": "9"},
    {"q": "Which is the longest river in the world?", "options": ["Amazon", "Nile", "Yangtze", "Mississippi"], "answer": "Nile"},
    {"q": "How many degrees are in a right angle?", "options": ["45", "90", "180", "360"], "answer": "90"},
    {"q": "What is the smallest prime number?", "options": ["0", "1", "2", "3"], "answer": "2"},
    {"q": "Which gas do humans need to breathe?", "options": ["Nitrogen", "Oxygen", "Carbon Dioxide", "Helium"], "answer": "Oxygen"},
    {"q": "What is the capital of France?", "options": ["Berlin", "Madrid", "Paris", "Rome"], "answer": "Paris"},
    {"q": "How many bones are in the adult human body?", "options": ["186", "206", "226", "246"], "answer": "206"},
    {"q": "What is 7 × 8?", "options": ["54", "56", "58", "64"], "answer": "56"},
    {"q": "Which is the largest mammal?", "options": ["Elephant", "Blue Whale", "Giraffe", "Hippo"], "answer": "Blue Whale"},
    {"q": "What is the boiling point of water at sea level (°C)?", "options": ["90", "100", "110", "120"], "answer": "100"},
]
